// Hershi Koritz Catering - Application JavaScript
const SUPABASE_URL = 'https://brmnbunyebbmdwvpaluz.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_2dGfebUekGwz2qWlSssjgw_JEXMVG5u';
const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
let cachedData = { categories: [], products: [], containers: [], customers: [], suppliers: [], tableItems: [], ingredients: [], packingRules: [] };

document.addEventListener('DOMContentLoaded', async () => {
    const today = new Date().toISOString().split('T')[0];
    document.getElementById('report-date').value = today;
    document.getElementById('filter-from-date').value = today;
    document.getElementById('filter-to-date').value = new Date(Date.now() + 30*24*60*60*1000).toISOString().split('T')[0];
    document.getElementById('payment-date').value = today;
    await loadAllData();
    setupFormHandlers();
    loadHomeStats();
});

async function loadAllData() {
    showLoading(true);
    try { await Promise.all([loadCategories(), loadProducts(), loadContainers(), loadCustomers(), loadSuppliers(), loadTableItems(), loadIngredients(), loadPackingRules()]); }
    catch (error) { console.error('Error loading data:', error); showToast('שגיאה בטעינת נתונים', 'error'); }
    showLoading(false);
}

async function loadCategories() { const { data, error } = await supabase.from('categories').select('*').order('name'); if (error) throw error; cachedData.categories = data || []; populateCategoryDropdowns(); renderCategoriesTable(); }
async function loadProducts() { const { data, error } = await supabase.from('products').select('*, categories(name, type)').order('name'); if (error) throw error; cachedData.products = data || []; populateProductDropdowns(); renderProductsTable(); }
async function loadContainers() { const { data, error } = await supabase.from('containers').select('*').order('name'); if (error) throw error; cachedData.containers = data || []; populateContainerDropdowns(); renderContainersTable(); }
async function loadCustomers() { const { data, error } = await supabase.from('customers').select('*').order('name'); if (error) throw error; cachedData.customers = data || []; populateCustomerDropdowns(); renderCustomersTable(); }
async function loadSuppliers() { const { data, error } = await supabase.from('suppliers').select('*').order('name'); if (error) throw error; cachedData.suppliers = data || []; populateSupplierDropdowns(); renderSuppliersTable(); }
async function loadTableItems() { const { data, error } = await supabase.from('table_items').select('*, suppliers(name)').order('name'); if (error) throw error; cachedData.tableItems = data || []; renderTableItemsTable(); }
async function loadIngredients() { const { data, error } = await supabase.from('ingredients').select('*').order('name'); if (error) throw error; cachedData.ingredients = data || []; populateIngredientDropdowns(); renderIngredientsTable(); }
async function loadPackingRules() { const { data, error } = await supabase.from('packing_rules').select('*, products(name), containers(name)').order('product_id'); if (error) throw error; cachedData.packingRules = data || []; renderPackingRulesTable(); }

async function loadOrders() {
    const fromDate = document.getElementById('filter-from-date').value;
    const toDate = document.getElementById('filter-to-date').value;
    const status = document.getElementById('filter-status').value;
    let query = supabase.from('orders').select('*, customers(name)').order('event_date', { ascending: true });
    if (fromDate) query = query.gte('event_date', fromDate);
    if (toDate) query = query.lte('event_date', toDate);
    if (status) query = query.eq('status', status);
    const { data, error } = await query;
    if (error) { showToast('שגיאה בטעינת הזמנות', 'error'); return; }
    renderOrdersTable(data || []);
}

async function loadHomeStats() {
    const today = new Date().toISOString().split('T')[0];
    const weekAgo = new Date(Date.now() - 7*24*60*60*1000).toISOString().split('T')[0];
    const { data: todayOrders } = await supabase.from('orders').select('id').eq('event_date', today);
    document.getElementById('stat-orders-today').textContent = todayOrders?.length || 0;
    const { data: weekOrders } = await supabase.from('orders').select('id').gte('event_date', weekAgo);
    document.getElementById('stat-orders-week').textContent = weekOrders?.length || 0;
    const { data: orders } = await supabase.from('orders').select('total_amount, paid_amount');
    const pendingTotal = (orders || []).reduce((sum, o) => sum + ((o.total_amount || 0) - (o.paid_amount || 0)), 0);
    document.getElementById('stat-pending-payments').textContent = '₪' + pendingTotal.toLocaleString();
    document.getElementById('stat-customers').textContent = cachedData.customers.length;
    const { data: todayOrdersData } = await supabase.from('orders').select('*, customers(name)').eq('event_date', today).order('delivery_time');
    renderTodayOrdersTable(todayOrdersData || []);
    loadOrdersForReportSelect();
}

async function loadOrdersForReportSelect() {
    const { data } = await supabase.from('orders').select('*, customers(name)').gte('event_date', new Date().toISOString().split('T')[0]).order('event_date');
    const select = document.getElementById('report-order-select');
    select.innerHTML = '<option value="">בחר הזמנה...</option>';
    (data || []).forEach(order => { const option = document.createElement('option'); option.value = order.id; option.textContent = '#' + order.order_number + ' - ' + (order.customers?.name || 'לקוח') + ' - ' + order.event_date; select.appendChild(option); });
}

function populateCategoryDropdowns() { const select = document.getElementById('product-category'); if (select) { const currentValue = select.value; select.innerHTML = '<option value="">בחר קטגוריה...</option>'; cachedData.categories.forEach(cat => { const option = document.createElement('option'); option.value = cat.id; option.textContent = cat.name + ' (' + getTypeLabel(cat.type) + ')'; select.appendChild(option); }); select.value = currentValue; } }
function populateProductDropdowns() { ['packing-rule-product', 'recipe-product'].forEach(id => { const select = document.getElementById(id); if (select) { select.innerHTML = '<option value="">בחר מוצר...</option>'; cachedData.products.forEach(p => { const option = document.createElement('option'); option.value = p.id; option.textContent = p.name; select.appendChild(option); }); } }); }
function populateContainerDropdowns() { const select = document.getElementById('packing-rule-container'); if (select) { select.innerHTML = '<option value="">בחר מיכל...</option>'; cachedData.containers.forEach(c => { const option = document.createElement('option'); option.value = c.id; option.textContent = c.name; select.appendChild(option); }); } }
function populateCustomerDropdowns() { const select = document.getElementById('order-customer'); if (select) { select.innerHTML = '<option value="">בחר לקוח...</option>'; cachedData.customers.forEach(c => { const option = document.createElement('option'); option.value = c.id; option.textContent = c.name; select.appendChild(option); }); } }
function populateSupplierDropdowns() { const select = document.getElementById('table-item-supplier'); if (select) { select.innerHTML = '<option value="">בחר ספק...</option>'; cachedData.suppliers.forEach(s => { const option = document.createElement('option'); option.value = s.id; option.textContent = s.name; select.appendChild(option); }); } }
function populateIngredientDropdowns() { const select = document.getElementById('recipe-ingredient'); if (select) { select.innerHTML = '<option value="">בחר חומר גלם...</option>'; cachedData.ingredients.forEach(i => { const option = document.createElement('option'); option.value = i.id; option.textContent = i.name + ' (' + i.unit + ')'; select.appendChild(option); }); } }

function renderCategoriesTable() { const tbody = document.getElementById('categories-table'); if (!tbody) return; if (cachedData.categories.length === 0) { tbody.innerHTML = '<tr><td colspan="3" class="text-center py-4">אין קטגוריות</td></tr>'; return; } tbody.innerHTML = cachedData.categories.map(cat => '<tr><td>' + cat.name + '</td><td><span class="badge bg-' + getTypeBadgeColor(cat.type) + '">' + getTypeLabel(cat.type) + '</span></td><td><button class="btn btn-sm btn-outline-primary btn-action" onclick="editCategory(\'' + cat.id + '\')"><i class="bi bi-pencil"></i></button> <button class="btn btn-sm btn-outline-danger btn-action" onclick="deleteCategory(\'' + cat.id + '\')"><i class="bi bi-trash"></i></button></td></tr>').join(''); }
function renderProductsTable(categoryFilter) { categoryFilter = categoryFilter || 'all'; const tbody = document.getElementById('products-table'); if (!tbody) return; let products = cachedData.products; if (categoryFilter !== 'all') products = products.filter(p => p.categories?.type === categoryFilter); if (products.length === 0) { tbody.innerHTML = '<tr><td colspan="6" class="text-center py-4">אין מוצרים</td></tr>'; return; } tbody.innerHTML = products.map(p => '<tr><td>' + p.name + '</td><td>' + (p.categories?.name || '-') + '</td><td>₪' + (p.price_per_portion || 0).toFixed(2) + '</td><td>' + (p.description || '-') + '</td><td><span class="badge bg-' + (p.is_active ? 'success' : 'secondary') + '">' + (p.is_active ? 'פעיל' : 'לא פעיל') + '</span></td><td><button class="btn btn-sm btn-outline-primary btn-action" onclick="editProduct(\'' + p.id + '\')"><i class="bi bi-pencil"></i></button> <button class="btn btn-sm btn-outline-danger btn-action" onclick="deleteProduct(\'' + p.id + '\')"><i class="bi bi-trash"></i></button></td></tr>').join(''); }
function renderContainersTable() { const tbody = document.getElementById('containers-table'); if (!tbody) return; if (cachedData.containers.length === 0) { tbody.innerHTML = '<tr><td colspan="5" class="text-center py-4">אין מיכלים</td></tr>'; return; } tbody.innerHTML = cachedData.containers.map(c => '<tr><td>' + c.name + '</td><td>' + (c.capacity_liters || '-') + '</td><td>' + (c.capacity_portions || '-') + '</td><td>' + (c.description || '-') + '</td><td><button class="btn btn-sm btn-outline-primary btn-action" onclick="editContainer(\'' + c.id + '\')"><i class="bi bi-pencil"></i></button> <button class="btn btn-sm btn-outline-danger btn-action" onclick="deleteContainer(\'' + c.id + '\')"><i class="bi bi-trash"></i></button></td></tr>').join(''); }
function renderCustomersTable() { const tbody = document.getElementById('customers-table'); if (!tbody) return; if (cachedData.customers.length === 0) { tbody.innerHTML = '<tr><td colspan="5" class="text-center py-4">אין לקוחות</td></tr>'; return; } tbody.innerHTML = cachedData.customers.map(c => '<tr><td>' + c.name + '</td><td>' + (c.phone || '-') + '</td><td>' + (c.email || '-') + '</td><td>' + (c.address || '-') + '</td><td><button class="btn btn-sm btn-outline-primary btn-action" onclick="editCustomer(\'' + c.id + '\')"><i class="bi bi-pencil"></i></button> <button class="btn btn-sm btn-outline-danger btn-action" onclick="deleteCustomer(\'' + c.id + '\')"><i class="bi bi-trash"></i></button></td></tr>').join(''); }
function renderSuppliersTable() { const tbody = document.getElementById('suppliers-table'); if (!tbody) return; if (cachedData.suppliers.length === 0) { tbody.innerHTML = '<tr><td colspan="5" class="text-center py-4">אין ספקים</td></tr>'; return; } tbody.innerHTML = cachedData.suppliers.map(s => '<tr><td>' + s.name + '</td><td><span class="badge bg-' + getSupplierTypeBadgeColor(s.type) + '">' + getSupplierTypeLabel(s.type) + '</span></td><td>' + (s.phone || '-') + '</td><td>' + (s.whatsapp ? '<a href="https://wa.me/' + s.whatsapp + '" target="_blank" class="btn btn-sm btn-success"><i class="bi bi-whatsapp"></i></a>' : '-') + '</td><td><button class="btn btn-sm btn-outline-primary btn-action" onclick="editSupplier(\'' + s.id + '\')"><i class="bi bi-pencil"></i></button> <button class="btn btn-sm btn-outline-danger btn-action" onclick="deleteSupplier(\'' + s.id + '\')"><i class="bi bi-trash"></i></button></td></tr>').join(''); }
function renderTableItemsTable() { const tbody = document.getElementById('table-items-table'); if (!tbody) return; if (cachedData.tableItems.length === 0) { tbody.innerHTML = '<tr><td colspan="5" class="text-center py-4">אין פריטי שולחן</td></tr>'; return; } tbody.innerHTML = cachedData.tableItems.map(item => '<tr><td>' + item.name + '</td><td>' + (item.category || '-') + '</td><td>' + (item.suppliers?.name || '-') + '</td><td>₪' + (item.price_per_unit || 0).toFixed(2) + '</td><td><button class="btn btn-sm btn-outline-primary btn-action" onclick="editTableItem(\'' + item.id + '\')"><i class="bi bi-pencil"></i></button> <button class="btn btn-sm btn-outline-danger btn-action" onclick="deleteTableItem(\'' + item.id + '\')"><i class="bi bi-trash"></i></button></td></tr>').join(''); }
function renderIngredientsTable() { const tbody = document.getElementById('ingredients-table'); if (!tbody) return; if (cachedData.ingredients.length === 0) { tbody.innerHTML = '<tr><td colspan="6" class="text-center py-4">אין חומרי גלם</td></tr>'; return; } tbody.innerHTML = cachedData.ingredients.map(i => '<tr class="' + (i.current_stock < i.min_stock ? 'table-warning' : '') + '"><td>' + i.name + '</td><td>' + getUnitLabel(i.unit) + '</td><td>₪' + (i.cost_per_unit || 0).toFixed(2) + '</td><td>' + (i.current_stock || 0) + '</td><td>' + (i.min_stock || 0) + '</td><td><button class="btn btn-sm btn-outline-primary btn-action" onclick="editIngredient(\'' + i.id + '\')"><i class="bi bi-pencil"></i></button> <button class="btn btn-sm btn-outline-danger btn-action" onclick="deleteIngredient(\'' + i.id + '\')"><i class="bi bi-trash"></i></button></td></tr>').join(''); }
function renderPackingRulesTable() { const tbody = document.getElementById('packing-rules-table'); if (!tbody) return; if (cachedData.packingRules.length === 0) { tbody.innerHTML = '<tr><td colspan="5" class="text-center py-4">אין כללי אריזה</td></tr>'; return; } tbody.innerHTML = cachedData.packingRules.map(r => '<tr><td>' + (r.products?.name || '-') + '</td><td>' + r.min_portions + '</td><td>' + r.max_portions + '</td><td>' + (r.containers?.name || '-') + '</td><td><button class="btn btn-sm btn-outline-primary btn-action" onclick="editPackingRule(\'' + r.id + '\')"><i class="bi bi-pencil"></i></button> <button class="btn btn-sm btn-outline-danger btn-action" onclick="deletePackingRule(\'' + r.id + '\')"><i class="bi bi-trash"></i></button></td></tr>').join(''); }

function renderOrdersTable(orders) { const tbody = document.getElementById('orders-table'); if (!tbody) return; if (orders.length === 0) { tbody.innerHTML = '<tr><td colspan="9" class="text-center py-4">אין הזמנות</td></tr>'; return; } tbody.innerHTML = orders.map(o => { const balance = (o.total_amount || 0) - (o.paid_amount || 0); return '<tr><td>' + o.order_number + '</td><td>' + (o.customers?.name || '-') + '</td><td>' + o.event_date + '</td><td>' + o.delivery_time + '</td><td>₪' + (o.total_amount || 0).toLocaleString() + '</td><td>₪' + (o.paid_amount || 0).toLocaleString() + '</td><td class="' + (balance > 0 ? 'text-danger fw-bold' : 'text-success') + '">₪' + balance.toLocaleString() + '</td><td><span class="badge bg-' + getStatusBadgeColor(o.status) + '">' + getStatusLabel(o.status) + '</span></td><td><button class="btn btn-sm btn-outline-info btn-action" onclick="viewOrder(\'' + o.id + '\')"><i class="bi bi-eye"></i></button> <button class="btn btn-sm btn-outline-success btn-action" onclick="openPaymentModal(\'' + o.id + '\')"><i class="bi bi-cash"></i></button> <button class="btn btn-sm btn-outline-primary btn-action" onclick="editOrder(\'' + o.id + '\')"><i class="bi bi-pencil"></i></button></td></tr>'; }).join(''); }
function renderTodayOrdersTable(orders) { const tbody = document.getElementById('today-orders-table'); if (!tbody) return; if (orders.length === 0) { tbody.innerHTML = '<tr><td colspan="5" class="text-center py-4">אין הזמנות להיום</td></tr>'; return; } tbody.innerHTML = orders.map(o => '<tr><td>' + o.order_number + '</td><td>' + (o.customers?.name || '-') + '</td><td>' + o.delivery_time + '</td><td><span class="badge bg-' + getStatusBadgeColor(o.status) + '">' + getStatusLabel(o.status) + '</span></td><td><button class="btn btn-sm btn-outline-primary" onclick="viewOrder(\'' + o.id + '\')"><i class="bi bi-eye"></i> צפה</button></td></tr>').join(''); }

function setupFormHandlers() {
    document.getElementById('customer-form')?.addEventListener('submit', async (e) => { e.preventDefault(); await saveCustomer(); });
    document.getElementById('product-form')?.addEventListener('submit', async (e) => { e.preventDefault(); await saveProduct(); });
    document.getElementById('category-form')?.addEventListener('submit', async (e) => { e.preventDefault(); await saveCategory(); });
    document.getElementById('container-form')?.addEventListener('submit', async (e) => { e.preventDefault(); await saveContainer(); });
    document.getElementById('supplier-form')?.addEventListener('submit', async (e) => { e.preventDefault(); await saveSupplier(); });
    document.getElementById('payment-form')?.addEventListener('submit', async (e) => { e.preventDefault(); await savePayment(); });
    document.getElementById('table-item-form')?.addEventListener('submit', async (e) => { e.preventDefault(); await saveTableItem(); });
    document.getElementById('packing-rule-form')?.addEventListener('submit', async (e) => { e.preventDefault(); await savePackingRule(); });
    document.getElementById('ingredient-form')?.addEventListener('submit', async (e) => { e.preventDefault(); await saveIngredient(); });
    document.getElementById('recipe-form')?.addEventListener('submit', async (e) => { e.preventDefault(); await saveRecipe(); });
    document.getElementById('new-order-form')?.addEventListener('submit', async (e) => { e.preventDefault(); await saveOrder(); });
    document.querySelectorAll('#productCategoryTabs .nav-link').forEach(tab => { tab.addEventListener('click', (e) => { e.preventDefault(); document.querySelectorAll('#productCategoryTabs .nav-link').forEach(t => t.classList.remove('active')); tab.classList.add('active'); renderProductsTable(tab.dataset.category); }); });
}

async function saveCustomer() { const id = document.getElementById('customer-id').value; const data = { name: document.getElementById('customer-name').value, phone: document.getElementById('customer-phone').value, email: document.getElementById('customer-email').value, address: document.getElementById('customer-address').value, notes: document.getElementById('customer-notes').value }; try { if (id) { await supabase.from('customers').update(data).eq('id', id); showToast('לקוח עודכן בהצלחה'); } else { await supabase.from('customers').insert([data]); showToast('לקוח נוצר בהצלחה'); } bootstrap.Modal.getInstance(document.getElementById('customerModal')).hide(); document.getElementById('customer-form').reset(); document.getElementById('customer-id').value = ''; await loadCustomers(); } catch (error) { showToast('שגיאה בשמירת לקוח', 'error'); } }
async function editCustomer(id) { const c = cachedData.customers.find(x => x.id === id); if (!c) return; document.getElementById('customer-id').value = c.id; document.getElementById('customer-name').value = c.name; document.getElementById('customer-phone').value = c.phone || ''; document.getElementById('customer-email').value = c.email || ''; document.getElementById('customer-address').value = c.address || ''; document.getElementById('customer-notes').value = c.notes || ''; new bootstrap.Modal(document.getElementById('customerModal')).show(); }
async function deleteCustomer(id) { if (!confirm('האם למחוק את הלקוח?')) return; try { await supabase.from('customers').delete().eq('id', id); showToast('לקוח נמחק'); await loadCustomers(); } catch (error) { showToast('שגיאה במחיקת לקוח', 'error'); } }

async function saveProduct() { const id = document.getElementById('product-id').value; const data = { name: document.getElementById('product-name').value, category_id: document.getElementById('product-category').value || null, price_per_portion: parseFloat(document.getElementById('product-price').value) || 0, description: document.getElementById('product-description').value, is_active: document.getElementById('product-active').checked }; try { if (id) { await supabase.from('products').update(data).eq('id', id); showToast('מוצר עודכן בהצלחה'); } else { await supabase.from('products').insert([data]); showToast('מוצר נוצר בהצלחה'); } bootstrap.Modal.getInstance(document.getElementById('productModal')).hide(); document.getElementById('product-form').reset(); document.getElementById('product-id').value = ''; await loadProducts(); } catch (error) { showToast('שגיאה בשמירת מוצר', 'error'); } }
async function editProduct(id) { const p = cachedData.products.find(x => x.id === id); if (!p) return; document.getElementById('product-id').value = p.id; document.getElementById('product-name').value = p.name; document.getElementById('product-category').value = p.category_id || ''; document.getElementById('product-price').value = p.price_per_portion || ''; document.getElementById('product-description').value = p.description || ''; document.getElementById('product-active').checked = p.is_active; new bootstrap.Modal(document.getElementById('productModal')).show(); }
async function deleteProduct(id) { if (!confirm('האם למחוק את המוצר?')) return; try { await supabase.from('products').delete().eq('id', id); showToast('מוצר נמחק'); await loadProducts(); } catch (error) { showToast('שגיאה במחיקת מוצר', 'error'); } }

async function saveCategory() { const id = document.getElementById('category-id').value; const data = { name: document.getElementById('category-name').value, type: document.getElementById('category-type').value }; try { if (id) { await supabase.from('categories').update(data).eq('id', id); showToast('קטגוריה עודכנה בהצלחה'); } else { await supabase.from('categories').insert([data]); showToast('קטגוריה נוצרה בהצלחה'); } bootstrap.Modal.getInstance(document.getElementById('categoryModal')).hide(); document.getElementById('category-form').reset(); document.getElementById('category-id').value = ''; await loadCategories(); } catch (error) { showToast('שגיאה בשמירת קטגוריה', 'error'); } }
async function editCategory(id) { const c = cachedData.categories.find(x => x.id === id); if (!c) return; document.getElementById('category-id').value = c.id; document.getElementById('category-name').value = c.name; document.getElementById('category-type').value = c.type; new bootstrap.Modal(document.getElementById('categoryModal')).show(); }
async function deleteCategory(id) { if (!confirm('האם למחוק את הקטגוריה?')) return; try { await supabase.from('categories').delete().eq('id', id); showToast('קטגוריה נמחקה'); await loadCategories(); } catch (error) { showToast('שגיאה במחיקת קטגוריה', 'error'); } }

async function saveContainer() { const id = document.getElementById('container-id').value; const data = { name: document.getElementById('container-name').value, capacity_liters: parseFloat(document.getElementById('container-liters').value) || null, capacity_portions: parseInt(document.getElementById('container-portions').value) || null, description: document.getElementById('container-description').value }; try { if (id) { await supabase.from('containers').update(data).eq('id', id); showToast('מיכל עודכן בהצלחה'); } else { await supabase.from('containers').insert([data]); showToast('מיכל נוצר בהצלחה'); } bootstrap.Modal.getInstance(document.getElementById('containerModal')).hide(); document.getElementById('container-form').reset(); document.getElementById('container-id').value = ''; await loadContainers(); } catch (error) { showToast('שגיאה בשמירת מיכל', 'error'); } }
async function editContainer(id) { const c = cachedData.containers.find(x => x.id === id); if (!c) return; document.getElementById('container-id').value = c.id; document.getElementById('container-name').value = c.name; document.getElementById('container-liters').value = c.capacity_liters || ''; document.getElementById('container-portions').value = c.capacity_portions || ''; document.getElementById('container-description').value = c.description || ''; new bootstrap.Modal(document.getElementById('containerModal')).show(); }
async function deleteContainer(id) { if (!confirm('האם למחוק את המיכל?')) return; try { await supabase.from('containers').delete().eq('id', id); showToast('מיכל נמחק'); await loadContainers(); } catch (error) { showToast('שגיאה במחיקת מיכל', 'error'); } }

async function saveSupplier() { const id = document.getElementById('supplier-id').value; const data = { name: document.getElementById('supplier-name').value, type: document.getElementById('supplier-type').value, phone: document.getElementById('supplier-phone').value, whatsapp: document.getElementById('supplier-whatsapp').value, email: document.getElementById('supplier-email').value, address: document.getElementById('supplier-address').value, notes: document.getElementById('supplier-notes').value }; try { if (id) { await supabase.from('suppliers').update(data).eq('id', id); showToast('ספק עודכן בהצלחה'); } else { await supabase.from('suppliers').insert([data]); showToast('ספק נוצר בהצלחה'); } bootstrap.Modal.getInstance(document.getElementById('supplierModal')).hide(); document.getElementById('supplier-form').reset(); document.getElementById('supplier-id').value = ''; await loadSuppliers(); } catch (error) { showToast('שגיאה בשמירת ספק', 'error'); } }
async function editSupplier(id) { const s = cachedData.suppliers.find(x => x.id === id); if (!s) return; document.getElementById('supplier-id').value = s.id; document.getElementById('supplier-name').value = s.name; document.getElementById('supplier-type').value = s.type; document.getElementById('supplier-phone').value = s.phone || ''; document.getElementById('supplier-whatsapp').value = s.whatsapp || ''; document.getElementById('supplier-email').value = s.email || ''; document.getElementById('supplier-address').value = s.address || ''; document.getElementById('supplier-notes').value = s.notes || ''; new bootstrap.Modal(document.getElementById('supplierModal')).show(); }
async function deleteSupplier(id) { if (!confirm('האם למחוק את הספק?')) return; try { await supabase.from('suppliers').delete().eq('id', id); showToast('ספק נמחק'); await loadSuppliers(); } catch (error) { showToast('שגיאה במחיקת ספק', 'error'); } }

async function saveTableItem() { const id = document.getElementById('table-item-id').value; const data = { name: document.getElementById('table-item-name').value, category: document.getElementById('table-item-category').value, supplier_id: document.getElementById('table-item-supplier').value || null, price_per_unit: parseFloat(document.getElementById('table-item-price').value) || 0 }; try { if (id) { await supabase.from('table_items').update(data).eq('id', id); showToast('פריט עודכן'); } else { await supabase.from('table_items').insert([data]); showToast('פריט נוצר'); } bootstrap.Modal.getInstance(document.getElementById('tableItemModal')).hide(); document.getElementById('table-item-form').reset(); document.getElementById('table-item-id').value = ''; await loadTableItems(); } catch (error) { showToast('שגיאה', 'error'); } }
async function editTableItem(id) { const item = cachedData.tableItems.find(x => x.id === id); if (!item) return; document.getElementById('table-item-id').value = item.id; document.getElementById('table-item-name').value = item.name; document.getElementById('table-item-category').value = item.category || ''; document.getElementById('table-item-supplier').value = item.supplier_id || ''; document.getElementById('table-item-price').value = item.price_per_unit || ''; new bootstrap.Modal(document.getElementById('tableItemModal')).show(); }
async function deleteTableItem(id) { if (!confirm('למחוק?')) return; try { await supabase.from('table_items').delete().eq('id', id); showToast('נמחק'); await loadTableItems(); } catch (error) { showToast('שגיאה', 'error'); } }

async function savePackingRule() { const id = document.getElementById('packing-rule-id').value; const data = { product_id: document.getElementById('packing-rule-product').value, min_portions: parseInt(document.getElementById('packing-rule-min').value), max_portions: parseInt(document.getElementById('packing-rule-max').value), container_id: document.getElementById('packing-rule-container').value }; try { if (id) { await supabase.from('packing_rules').update(data).eq('id', id); } else { await supabase.from('packing_rules').insert([data]); } showToast('נשמר'); bootstrap.Modal.getInstance(document.getElementById('packingRuleModal')).hide(); document.getElementById('packing-rule-form').reset(); document.getElementById('packing-rule-id').value = ''; await loadPackingRules(); } catch (error) { showToast('שגיאה', 'error'); } }
async function editPackingRule(id) { const r = cachedData.packingRules.find(x => x.id === id); if (!r) return; document.getElementById('packing-rule-id').value = r.id; document.getElementById('packing-rule-product').value = r.product_id; document.getElementById('packing-rule-min').value = r.min_portions; document.getElementById('packing-rule-max').value = r.max_portions; document.getElementById('packing-rule-container').value = r.container_id; new bootstrap.Modal(document.getElementById('packingRuleModal')).show(); }
async function deletePackingRule(id) { if (!confirm('למחוק?')) return; try { await supabase.from('packing_rules').delete().eq('id', id); showToast('נמחק'); await loadPackingRules(); } catch (error) { showToast('שגיאה', 'error'); } }

async function saveIngredient() { const id = document.getElementById('ingredient-id').value; const data = { name: document.getElementById('ingredient-name').value, unit: document.getElementById('ingredient-unit').value, cost_per_unit: parseFloat(document.getElementById('ingredient-cost').value) || 0, current_stock: parseFloat(document.getElementById('ingredient-stock').value) || 0, min_stock: parseFloat(document.getElementById('ingredient-min-stock').value) || 0 }; try { if (id) { await supabase.from('ingredients').update(data).eq('id', id); } else { await supabase.from('ingredients').insert([data]); } showToast('נשמר'); bootstrap.Modal.getInstance(document.getElementById('ingredientModal')).hide(); document.getElementById('ingredient-form').reset(); document.getElementById('ingredient-id').value = ''; await loadIngredients(); } catch (error) { showToast('שגיאה', 'error'); } }
async function editIngredient(id) { const i = cachedData.ingredients.find(x => x.id === id); if (!i) return; document.getElementById('ingredient-id').value = i.id; document.getElementById('ingredient-name').value = i.name; document.getElementById('ingredient-unit').value = i.unit; document.getElementById('ingredient-cost').value = i.cost_per_unit || ''; document.getElementById('ingredient-stock').value = i.current_stock || ''; document.getElementById('ingredient-min-stock').value = i.min_stock || ''; new bootstrap.Modal(document.getElementById('ingredientModal')).show(); }
async function deleteIngredient(id) { if (!confirm('למחוק?')) return; try { await supabase.from('ingredients').delete().eq('id', id); showToast('נמחק'); await loadIngredients(); } catch (error) { showToast('שגיאה', 'error'); } }

async function saveRecipe() { const id = document.getElementById('recipe-id').value; const data = { product_id: document.getElementById('recipe-product').value, ingredient_id: document.getElementById('recipe-ingredient').value, quantity_per_portion: parseFloat(document.getElementById('recipe-quantity').value), unit: document.getElementById('recipe-unit').value }; try { if (id) { await supabase.from('recipes').update(data).eq('id', id); } else { await supabase.from('recipes').insert([data]); } showToast('נשמר'); bootstrap.Modal.getInstance(document.getElementById('recipeModal')).hide(); document.getElementById('recipe-form').reset(); } catch (error) { showToast('שגיאה', 'error'); } }

async function savePayment() { const orderId = document.getElementById('payment-order-id').value; const data = { order_id: orderId, amount: parseFloat(document.getElementById('payment-amount').value), payment_method: document.getElementById('payment-method').value, payment_date: document.getElementById('payment-date').value, reference: document.getElementById('payment-reference').value, notes: document.getElementById('payment-notes').value }; try { await supabase.from('payments').insert([data]); const { data: orderData } = await supabase.from('orders').select('paid_amount').eq('id', orderId).single(); const newPaidAmount = (orderData?.paid_amount || 0) + data.amount; await supabase.from('orders').update({ paid_amount: newPaidAmount }).eq('id', orderId); showToast('תשלום נרשם'); bootstrap.Modal.getInstance(document.getElementById('paymentModal')).hide(); document.getElementById('payment-form').reset(); loadOrders(); loadHomeStats(); } catch (error) { showToast('שגיאה', 'error'); } }
function openPaymentModal(orderId) { document.getElementById('payment-order-id').value = orderId; document.getElementById('payment-date').value = new Date().toISOString().split('T')[0]; new bootstrap.Modal(document.getElementById('paymentModal')).show(); }
Spinner').classList.toggle('show', show); }

function showToast(message, type) { type = type || 'success'; const container = document.querySelector('.toast-container'); const toastId = 'toast-' + Date.now(); container.insertAdjacentHTML('beforeend', '<div id="' + toastId + '" class="toast align-items-center text-bg-' + (type === 'error' ? 'danger' : 'success') + ' border-0" role="alert"><div class="d-flex"><div class="toast-body"><i class="bi bi-' + (type === 'error' ? 'x-circle' : 'check-circle') + ' me-2"></i>' + message + '</div><button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button></div></div>'); const toastElement = document.getElementById(toastId); const toast = new bootstrap.Toast(toastElement, { delay: 3000 }); toast.show(); toastElement.addEventListener('hidden.bs.toast', function() { toastElement.remove(); }); }

function showQuickCustomerModal() { document.getElementById('customer-id').value = ''; document.getElementById('customer-form').reset(); new bootstrap.Modal(document.getElementById('customerModal')).show(); }

function getTypeLabel(type) { const labels = { 'hot': 'פס חם', 'cold': 'פס קר', 'bakery': 'קונדיטוריה', 'table': 'פריטי שולחן' }; return labels[type] || type; }
function getTypeBadgeColor(type) { const colors = { 'hot': 'danger', 'cold': 'info', 'bakery': 'warning', 'table': 'secondary' }; return colors[type] || 'secondary'; }
function getSupplierTypeLabel(type) { const labels = { 'bakery': 'קונדיטוריה', 'table': 'פריטי שולחן', 'ingredients': 'חומרי גלם', 'other': 'אחר' }; return labels[type] || type; }
function getSupplierTypeBadgeColor(type) { const colors = { 'bakery': 'warning', 'table': 'secondary', 'ingredients': 'success', 'other': 'dark' }; return colors[type] || 'secondary'; }
function getStatusLabel(status) { const labels = { 'new': 'חדש', 'confirmed': 'מאושר', 'in_production': 'בייצור', 'ready': 'מוכן', 'delivered': 'נמסר', 'cancelled': 'בוטל' }; return labels[status] || status; }
function getStatusBadgeColor(status) { const colors = { 'new': 'primary', 'confirmed': 'info', 'in_production': 'warning', 'ready': 'success', 'delivered': 'secondary', 'cancelled': 'danger' }; return colors[status] || 'secondary'; }
function getUnitLabel(unit) { const labels = { 'gram': 'גרם', 'kg': 'ק"ג', 'liter': 'ליטר', 'ml': 'מ"ל', 'unit': 'יחידה' }; return labels[unit] || unit; }
